### ISSUE TITLE
 test: detection time per frame?

### ISSUE THREAD

**Issue by yhl2018** [crisie/RecurrentGaze#2]

**Comment by crisie** [comment]
That would depend on the pc and gpu configuration. With my setup (GeForce RTX 2080 TI) and `batch_size=1`, I obtain the following results:

```
Mean time elapsed per frame with NFEL5836 model:  0.1394 s
Mean time elapsed per frame with NFEL5836GRU model:  0.1962 s
```

However, when increasing the batch_size the elapsed time decreases. For instance, with `batch_size=8`:

```
Mean time elapsed per frame with NFEL5836 model:  0.042 s
Mean time elapsed per frame with NFEL5836GRU model:  0.084 s
```
