### ISSUE TITLE
Testonline Issue OpenFaceDLL.so file

### ISSUE THREAD

**Issue by nicole7han** [crisie/RecurrentGaze#5]
Hi,

I was trying to do some gaze estimation test on a simple image. I have openface compiled. 

When I run it, the error says: 
/OpenFace-master/OpenFaceDLL.so: cannot open shared object file: No such file or directory

What exactly is this OpenFaceDLL.so file?

**Comment by crisie** [comment]
Hi!

I've updated the Readme file to explain how ```TestOnline.py``` works. This DLL/so file is a shared library to use OpenFace within python applications. Check this link for install instructions: https://github.com/crisie/OpenFaceWrapper. You will need to modify the ```openfacewrapper_path``` in ```TestOnline.py``` accordingly. Check also the new ReadMe file on what other third-party libraries are required.

Right now, only NFEL5836_2918 model (static model) is compatible with the current online code. 

Let me know if you have any trouble making it work.

**Comment by nicole7han** [comment]
Hi Crisie,

Thank you so much for your reply! I’ll try that!

Best,
Nicole
